[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
ForcePartition = "9741c49f-01d7-4d13-b632-54dd32ae0596"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Gismo = "f019f137-166b-4455-b646-ee200b009b83"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ParametricBodies = "06905c2e-4b4a-4765-8bb9-c6b6b2b99b1d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
WaterLily = "ed894a53-35f9-47f1-b17f-85db9237eebd"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
